### ISSUE TITLE
MVC Test

### ISSUE THREAD

**Issue by Juhongseok** [Project-MO-A/Backend#13]
## Description
UserController 구현한 기능에 대해 MVC TEST 진행

## TODO
- [x] 홍석 완료 여부
- [x] 기우 완료 여부

----
둘 다 완료 후 Issue 닫기
가능하면 3/13 월요일까지 진행

**Comment by KAispread** [comment]
All MVC tests successful

**Comment by KAispread** [comment]
All MVC tests successful
