### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by Juhongseok** [Project-MO-A/Backend#14]
## Description
코드 정리 및 기능 추가(있다면)

## TODO
- [x] 홍석 완료 여부
- [x] 기우 완료 여부

----
둘 다 완료 후 Issue 닫기
가능하면 3/13 월요일까지 진행

**Comment by KAispread** [comment]
비밀번호 수정 API 따로 만들고 닫겠습니다

**Comment by Juhongseok** [comment]
알겠습니다

**Comment by KAispread** [comment]
리팩토링 완료
