### ISSUE TITLE
[feat] 중심 장소 추천 기능 구현

### ISSUE THREAD

**Issue by KAispread** [Project-MO-A/Backend#37]
## TO DO
- [x] 그라함 알고리즘을 이용하여 중심점을 찾는다.
- [ ] 중심점에서 근처 지하철역과 카페를 검색(kakaoAPI 사용) 및 추천

## 참고 사항
- API 호출하는 방식은 restTemplate이나 WebClient (권장) 사용해보는 것으로 함

**Comment by Juhongseok** [comment]
Issue #66 에서 구현
--> 해당 Issue 닫고 새로운 Issue로 이동
