### ISSUE TITLE
기타 수정사항

### ISSUE THREAD

**Issue by Juhongseok** [Project-MO-A/Backend#66]
### Recruitment
- [x] 조회 시 해시태그 추가

### User
**유저 정보**
- [x] 관심 글, 작성 글 필드 변경 (카테고리, 태그, 제목, 작성일, 댓글 수, 모집 상태)

### Notice
- [x] 작성 시 내용, 투표 여부만 입력
- [x] 투표 완료 시 추천 위치 정보 전달 (그라함 알고리즘 사용)

### User
**활동 내역**

- [x] 승인된 프로젝트 상태 명 Complete(모집 완료) -> 진행 중 변경
- [x] 기타 프로젝트 -> 지원 분야 추가

## 공동
- [x] 댓글 기능 추가

**Comment by KAispread** [comment]
Recruitment 조회시 해시 태그명도 함께 조회되게끔 이미 구현되어있는데, 조회가 안되는 문제가 있었나요?

**Comment by KAispread** [comment]
맨 처음 task의 해시태그가 Category 맞죠?
