### ISSUE TITLE
fix & refactor:  모집글 / 공지사항 api, 에러 수정

### ISSUE THREAD

**Issue by KAispread** [Project-MO-A/Backend#87]
## TO DO
- [x] 시간 조율 APi 수정
- [x] 모집글 삭제 500 에러 해결
- [x] 공지사항 전체 조회 데이터 변경
- [x] 모집글 댓글 조회 데이터 변경
- [x] 모집글 댓글 수정 확인
- [x] 모집글 상태변경 확인

**Comment by KAispread** [comment]
@Juhongseok 
혹시 모집글 삭제랑 공지사항 조회 데이터 변경 작업 해주실 수 있을까요??
시간 조율 API 수정하는데, PossibleTime 테이블 필드를 바꿔야되서 좀 걸릴 것 같아요

Discussion url 입니다
https://github.com/orgs/Project-MO-A/discussions/7

**Comment by Juhongseok** [comment]
네! 알겠습니다

**Comment by Juhongseok** [comment]
@KAispread 
근데 테이블 필드가 많이 수정되나요??
LocalTime -> LocalDateTime으로 변경해주면 되지 않을까요???

**Comment by Juhongseok** [comment]
Day는 없어져도 endTime은 살린 상태에서 반환 값만 변경할 수 있지 않을까요?

|applimentMemberId|startTime|endTime|
|:---:|:---:|:---:|
|1|2023-03-30T11:00:00.000Z|2023-03-30T14:00:00.000Z|
|1|2023-03-31T11:00:00.000Z|2023-03-30T14:00:00.000Z|

이런 식으로 데이터 들어가면 반환 시에만 11시에서 14시까지 `LocalDateTime.plusMinutes`를 사용해서 30분 씩 더해서 값을 반환할 수 있을 거 같은데요?

그러면 response DTO 값 설정 부분만 수정하면 크게 바뀌진 않을 거 같아요

물론 LocalTime에서 LocalDateTime으로 변경하는 부분은 바뀌긴 하겠지만요..
