### ISSUE TITLE
Github Action CICD 진행

### ISSUE THREAD

**Issue by Juhongseok** [Project-MO-A/Backend#95]
## TODO
- [x] Github Action

**Comment by KAispread** [comment]
@Juhongseok

dev 브랜치에 PR을 올리면 CI,
dev 브랜치에 코드가 push (merge)되면 CI/CD 동작이 수행되도록 변경했습니다.

AWS CodeDeploy 서비스에서 배포 내역 보시면 이력을 확인하실 수 있습니다.
